import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '@/styles/reset.scss'
import '@/styles/ui.scss'
import Head from 'next/head'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" type="text/css" href="./reset.css" />
        <link rel="stylesheet" type="text/css" href="./ui.css" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
